import type { FormDefinition } from '../types'

export const anlageVorsorgeaufwand2025: FormDefinition = {
  id: 'anlage_vorsorgeaufwand',
  name: 'Anlage Vorsorgeaufwand 2025',
  description: 'Für Kranken-, Renten- und Lebensversicherungsbeiträge',
  triggerKeywords: ['krankenversicherung', 'rentenversicherung', 'lebensversicherung', 'vorsorge', 'pflegeversicherung', 'versicherung'],
  fields: [
    {
      id: 'rvBeitragArbeitnehmer',
      label: 'Rentenversicherungsbeitrag Arbeitnehmeranteil',
      question: 'Wie hoch war Ihr Arbeitnehmeranteil zur gesetzlichen Rentenversicherung? Diesen Betrag finden Sie auf Ihrer Lohnsteuerbescheinigung.',
      type: 'number',
      required: false,
      hint: 'In Euro',
    },
    {
      id: 'kvBeitragGesetzlich',
      label: 'Beiträge zur gesetzlichen Krankenversicherung',
      question: 'Wie hoch waren Ihre Beiträge zur gesetzlichen Krankenversicherung im Jahr 2025?',
      type: 'number',
      required: false,
      hint: 'In Euro, inklusive Zusatzbeitrag',
    },
    {
      id: 'kvBeitragPrivat',
      label: 'Beiträge zur privaten Krankenversicherung',
      question: 'Haben Sie eine private Krankenversicherung? Wenn ja, wie hoch waren die Gesamtbeiträge im Jahr 2025?',
      type: 'number',
      required: false,
      hint: 'In Euro, nur Basiskrankenversicherung ist vollständig absetzbar',
    },
    {
      id: 'pflegeversicherungBeitrag',
      label: 'Beiträge zur Pflegeversicherung',
      question: 'Wie hoch waren Ihre Beiträge zur Pflegeversicherung?',
      type: 'number',
      required: false,
      hint: 'In Euro',
    },
    {
      id: 'arbeitslosenversicherung',
      label: 'Beiträge zur Arbeitslosenversicherung',
      question: 'Wie hoch waren Ihre Beiträge zur Arbeitslosenversicherung?',
      type: 'number',
      required: false,
      hint: 'In Euro',
    },
    {
      id: 'riesterRente',
      label: 'Riester-Rente Eigenbeiträge',
      question: 'Haben Sie in eine Riester-Rente eingezahlt? Wenn ja, wie viel im Jahr 2025?',
      type: 'number',
      required: false,
      hint: 'In Euro, eigene Beiträge ohne Zulage',
    },
    {
      id: 'ruerupRente',
      label: 'Rürup-Rente / Basisrente Beiträge',
      question: 'Haben Sie Beiträge zu einer Rürup- oder Basisrente gezahlt?',
      type: 'number',
      required: false,
      hint: 'In Euro',
    },
    {
      id: 'sonstigeVersicherungen',
      label: 'Sonstige Vorsorgeaufwendungen',
      question: 'Haben Sie weitere Versicherungsbeiträge wie Haftpflicht, Unfall oder Berufsunfähigkeit gezahlt?',
      type: 'number',
      required: false,
      hint: 'In Euro, Summe aller weiteren Versicherungen',
    },
  ],
}
