import type { FormDefinition } from '../types'

export const anlageN2025: FormDefinition = {
  id: 'anlage_n',
  name: 'Anlage N – Einkünfte aus nichtselbständiger Arbeit 2025',
  description: 'Für Arbeitnehmer mit Lohn- oder Gehalteseinkünften',
  triggerKeywords: ['angestellt', 'arbeitnehmer', 'gehalt', 'lohn', 'arbeitgeber', 'lohnsteuer', 'arbeit'],
  fields: [
    {
      id: 'arbeitgeberName',
      label: 'Name des Arbeitgebers',
      question: 'Wie heißt Ihr Arbeitgeber?',
      type: 'text',
      required: true,
    },
    {
      id: 'bruttoArbeitslohn',
      label: 'Bruttoarbeitslohn',
      question: 'Wie hoch war Ihr Bruttoarbeitslohn im Jahr 2025? Sie finden diesen Betrag auf Ihrer Lohnsteuerbescheinigung.',
      type: 'number',
      required: true,
      hint: 'In Euro, ohne Cent (z.B. 45000)',
    },
    {
      id: 'einbehalteneKirchensteuer',
      label: 'Einbehaltene Kirchensteuer',
      question: 'Wie viel Kirchensteuer wurde einbehalten? Falls keine, sagen Sie einfach Null.',
      type: 'number',
      required: false,
      hint: 'In Euro',
    },
    {
      id: 'werbungskosten',
      label: 'Werbungskosten',
      question: 'Hatten Sie berufliche Ausgaben, die über den Pauschbetrag von 1.230 Euro hinausgehen? Zum Beispiel Fahrtkosten, Arbeitsmittel oder Fortbildungen?',
      type: 'boolean',
      required: true,
    },
    {
      id: 'entfernungWohnung',
      label: 'Entfernung Wohnung – Arbeitsstätte (km)',
      question: 'Wie viele Kilometer beträgt die einfache Entfernung von Ihrer Wohnung zur Arbeit?',
      type: 'number',
      required: false,
      hint: 'Einfache Strecke in km',
    },
    {
      id: 'arbeitstage',
      label: 'Arbeitstage im Jahr',
      question: 'An wie vielen Tagen sind Sie im Jahr 2025 zur Arbeit gefahren?',
      type: 'number',
      required: false,
      hint: 'Anzahl der Arbeitstage',
    },
    {
      id: 'homeoffice',
      label: 'Homeoffice-Tage',
      question: 'Wie viele Tage haben Sie im Jahr 2025 im Homeoffice gearbeitet?',
      type: 'number',
      required: false,
      hint: 'Maximal 210 Tage absetzbar à 6 Euro',
    },
    {
      id: 'arbeitsmittelKosten',
      label: 'Kosten für Arbeitsmittel',
      question: 'Haben Sie Arbeitsmittel wie Laptop, Fachliteratur oder Bürobedarf selbst bezahlt? Wenn ja, wie viel insgesamt?',
      type: 'number',
      required: false,
      hint: 'In Euro',
    },
    {
      id: 'fortbildungskosten',
      label: 'Fortbildungskosten',
      question: 'Hatten Sie Kosten für berufliche Fortbildungen oder Weiterbildungen?',
      type: 'number',
      required: false,
      hint: 'In Euro',
    },
  ],
}
