import type { FormDefinition } from '../types'

export const estA2025: FormDefinition = {
  id: 'est_1_a',
  name: 'ESt 1 A – Einkommensteuererklärung 2025',
  description: 'Hauptformular für die Einkommensteuererklärung',
  triggerKeywords: ['steuererklärung', 'einkommensteuer', 'grundformular', 'hauptformular'],
  fields: [
    {
      id: 'steuerNr',
      label: 'Steuernummer',
      question: 'Was ist Ihre Steuernummer? Sie finden diese auf alten Steuerbescheiden.',
      type: 'text',
      required: false,
      hint: 'Format: 12/345/67890',
    },
    {
      id: 'identNr',
      label: 'Steuerliche Identifikationsnummer',
      question: 'Was ist Ihre Steuerliche Identifikationsnummer? Das ist eine 11-stellige Zahl, die Sie per Brief vom Bundeszentralamt erhalten haben.',
      type: 'text',
      required: true,
      hint: '11-stellige Nummer',
    },
    {
      id: 'veranlagungsjahr',
      label: 'Veranlagungsjahr',
      question: 'Für welches Jahr möchten Sie die Steuererklärung abgeben?',
      type: 'number',
      required: true,
    },
    {
      id: 'vorname',
      label: 'Vorname',
      question: 'Wie lautet Ihr Vorname?',
      type: 'text',
      required: true,
    },
    {
      id: 'nachname',
      label: 'Nachname',
      question: 'Wie lautet Ihr Nachname?',
      type: 'text',
      required: true,
    },
    {
      id: 'geburtsdatum',
      label: 'Geburtsdatum',
      question: 'Was ist Ihr Geburtsdatum?',
      type: 'date',
      required: true,
      hint: 'Format: TT.MM.JJJJ',
    },
    {
      id: 'strasse',
      label: 'Straße und Hausnummer',
      question: 'Wie lautet Ihre aktuelle Straße und Hausnummer?',
      type: 'text',
      required: true,
    },
    {
      id: 'plzOrt',
      label: 'PLZ und Ort',
      question: 'Wie lauten Ihre Postleitzahl und Ihr Wohnort?',
      type: 'text',
      required: true,
    },
    {
      id: 'familienstand',
      label: 'Familienstand',
      question: 'Was ist Ihr Familienstand? Sind Sie ledig, verheiratet, geschieden oder verwitwet?',
      type: 'select',
      options: ['ledig', 'verheiratet', 'getrennt lebend', 'geschieden', 'verwitwet'],
      required: true,
    },
    {
      id: 'iban',
      label: 'IBAN für Steuererstattung',
      question: 'Auf welches Konto soll eine mögliche Steuererstattung überwiesen werden? Bitte nennen Sie Ihre IBAN.',
      type: 'text',
      required: false,
      hint: 'Format: DE12 3456 7890 1234 5678 90',
    },
  ],
}
